/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOsSplatRouteImport } from './routes/api/os/$'
import { Route as ApiNotificationsUnreadCountRouteImport } from './routes/api/notifications/unread-count'
import { Route as ApiNotificationsTestRouteImport } from './routes/api/notifications/test'
import { Route as ApiNotificationsSettingsRouteImport } from './routes/api/notifications/settings'
import { Route as ApiNotificationsMarkAllReadRouteImport } from './routes/api/notifications/mark-all-read'
import { Route as ApiNotificationsInboxRouteImport } from './routes/api/notifications/inbox'
import { Route as ApiNotificationsConfigRouteImport } from './routes/api/notifications/config'
import { Route as ApiAuthSiteRouteImport } from './routes/api/auth/site'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOsSplatRoute = ApiOsSplatRouteImport.update({
  id: '/api/os/$',
  path: '/api/os/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsUnreadCountRoute =
  ApiNotificationsUnreadCountRouteImport.update({
    id: '/api/notifications/unread-count',
    path: '/api/notifications/unread-count',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationsTestRoute = ApiNotificationsTestRouteImport.update({
  id: '/api/notifications/test',
  path: '/api/notifications/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsSettingsRoute =
  ApiNotificationsSettingsRouteImport.update({
    id: '/api/notifications/settings',
    path: '/api/notifications/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationsMarkAllReadRoute =
  ApiNotificationsMarkAllReadRouteImport.update({
    id: '/api/notifications/mark-all-read',
    path: '/api/notifications/mark-all-read',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationsInboxRoute = ApiNotificationsInboxRouteImport.update({
  id: '/api/notifications/inbox',
  path: '/api/notifications/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsConfigRoute = ApiNotificationsConfigRouteImport.update({
  id: '/api/notifications/config',
  path: '/api/notifications/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSiteRoute = ApiAuthSiteRouteImport.update({
  id: '/api/auth/site',
  path: '/api/auth/site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backup': typeof BackupRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/more': typeof MoreRoute
  '/preview': typeof PreviewRoute
  '/programs': typeof ProgramsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/stations': typeof StationsRoute
  '/tools': typeof ToolsRoute
  '/zones': typeof ZonesRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/site': typeof ApiAuthSiteRoute
  '/api/notifications/config': typeof ApiNotificationsConfigRoute
  '/api/notifications/inbox': typeof ApiNotificationsInboxRoute
  '/api/notifications/mark-all-read': typeof ApiNotificationsMarkAllReadRoute
  '/api/notifications/settings': typeof ApiNotificationsSettingsRoute
  '/api/notifications/test': typeof ApiNotificationsTestRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/os/$': typeof ApiOsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backup': typeof BackupRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/more': typeof MoreRoute
  '/preview': typeof PreviewRoute
  '/programs': typeof ProgramsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/stations': typeof StationsRoute
  '/tools': typeof ToolsRoute
  '/zones': typeof ZonesRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/site': typeof ApiAuthSiteRoute
  '/api/notifications/config': typeof ApiNotificationsConfigRoute
  '/api/notifications/inbox': typeof ApiNotificationsInboxRoute
  '/api/notifications/mark-all-read': typeof ApiNotificationsMarkAllReadRoute
  '/api/notifications/settings': typeof ApiNotificationsSettingsRoute
  '/api/notifications/test': typeof ApiNotificationsTestRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/os/$': typeof ApiOsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backup': typeof BackupRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forecast': typeof ForecastRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/more': typeof MoreRoute
  '/preview': typeof PreviewRoute
  '/programs': typeof ProgramsRoute
  '/sensors': typeof SensorsRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/stations': typeof StationsRoute
  '/tools': typeof ToolsRoute
  '/zones': typeof ZonesRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/site': typeof ApiAuthSiteRoute
  '/api/notifications/config': typeof ApiNotificationsConfigRoute
  '/api/notifications/inbox': typeof ApiNotificationsInboxRoute
  '/api/notifications/mark-all-read': typeof ApiNotificationsMarkAllReadRoute
  '/api/notifications/settings': typeof ApiNotificationsSettingsRoute
  '/api/notifications/test': typeof ApiNotificationsTestRoute
  '/api/notifications/unread-count': typeof ApiNotificationsUnreadCountRoute
  '/api/os/$': typeof ApiOsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/backup'
    | '/diagnostics'
    | '/forecast'
    | '/history'
    | '/login'
    | '/logs'
    | '/more'
    | '/preview'
    | '/programs'
    | '/sensors'
    | '/settings'
    | '/sites'
    | '/stations'
    | '/tools'
    | '/zones'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/site'
    | '/api/notifications/config'
    | '/api/notifications/inbox'
    | '/api/notifications/mark-all-read'
    | '/api/notifications/settings'
    | '/api/notifications/test'
    | '/api/notifications/unread-count'
    | '/api/os/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/backup'
    | '/diagnostics'
    | '/forecast'
    | '/history'
    | '/login'
    | '/logs'
    | '/more'
    | '/preview'
    | '/programs'
    | '/sensors'
    | '/settings'
    | '/sites'
    | '/stations'
    | '/tools'
    | '/zones'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/site'
    | '/api/notifications/config'
    | '/api/notifications/inbox'
    | '/api/notifications/mark-all-read'
    | '/api/notifications/settings'
    | '/api/notifications/test'
    | '/api/notifications/unread-count'
    | '/api/os/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/backup'
    | '/diagnostics'
    | '/forecast'
    | '/history'
    | '/login'
    | '/logs'
    | '/more'
    | '/preview'
    | '/programs'
    | '/sensors'
    | '/settings'
    | '/sites'
    | '/stations'
    | '/tools'
    | '/zones'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/auth/site'
    | '/api/notifications/config'
    | '/api/notifications/inbox'
    | '/api/notifications/mark-all-read'
    | '/api/notifications/settings'
    | '/api/notifications/test'
    | '/api/notifications/unread-count'
    | '/api/os/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BackupRoute: typeof BackupRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ForecastRoute: typeof ForecastRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MoreRoute: typeof MoreRoute
  PreviewRoute: typeof PreviewRoute
  ProgramsRoute: typeof ProgramsRoute
  SensorsRoute: typeof SensorsRoute
  SettingsRoute: typeof SettingsRoute
  SitesRoute: typeof SitesRoute
  StationsRoute: typeof StationsRoute
  ToolsRoute: typeof ToolsRoute
  ZonesRoute: typeof ZonesRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSiteRoute: typeof ApiAuthSiteRoute
  ApiNotificationsConfigRoute: typeof ApiNotificationsConfigRoute
  ApiNotificationsInboxRoute: typeof ApiNotificationsInboxRoute
  ApiNotificationsMarkAllReadRoute: typeof ApiNotificationsMarkAllReadRoute
  ApiNotificationsSettingsRoute: typeof ApiNotificationsSettingsRoute
  ApiNotificationsTestRoute: typeof ApiNotificationsTestRoute
  ApiNotificationsUnreadCountRoute: typeof ApiNotificationsUnreadCountRoute
  ApiOsSplatRoute: typeof ApiOsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/os/$': {
      id: '/api/os/$'
      path: '/api/os/$'
      fullPath: '/api/os/$'
      preLoaderRoute: typeof ApiOsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/unread-count': {
      id: '/api/notifications/unread-count'
      path: '/api/notifications/unread-count'
      fullPath: '/api/notifications/unread-count'
      preLoaderRoute: typeof ApiNotificationsUnreadCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/test': {
      id: '/api/notifications/test'
      path: '/api/notifications/test'
      fullPath: '/api/notifications/test'
      preLoaderRoute: typeof ApiNotificationsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/settings': {
      id: '/api/notifications/settings'
      path: '/api/notifications/settings'
      fullPath: '/api/notifications/settings'
      preLoaderRoute: typeof ApiNotificationsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/mark-all-read': {
      id: '/api/notifications/mark-all-read'
      path: '/api/notifications/mark-all-read'
      fullPath: '/api/notifications/mark-all-read'
      preLoaderRoute: typeof ApiNotificationsMarkAllReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/inbox': {
      id: '/api/notifications/inbox'
      path: '/api/notifications/inbox'
      fullPath: '/api/notifications/inbox'
      preLoaderRoute: typeof ApiNotificationsInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/config': {
      id: '/api/notifications/config'
      path: '/api/notifications/config'
      fullPath: '/api/notifications/config'
      preLoaderRoute: typeof ApiNotificationsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/site': {
      id: '/api/auth/site'
      path: '/api/auth/site'
      fullPath: '/api/auth/site'
      preLoaderRoute: typeof ApiAuthSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BackupRoute: BackupRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ForecastRoute: ForecastRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MoreRoute: MoreRoute,
  PreviewRoute: PreviewRoute,
  ProgramsRoute: ProgramsRoute,
  SensorsRoute: SensorsRoute,
  SettingsRoute: SettingsRoute,
  SitesRoute: SitesRoute,
  StationsRoute: StationsRoute,
  ToolsRoute: ToolsRoute,
  ZonesRoute: ZonesRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSiteRoute: ApiAuthSiteRoute,
  ApiNotificationsConfigRoute: ApiNotificationsConfigRoute,
  ApiNotificationsInboxRoute: ApiNotificationsInboxRoute,
  ApiNotificationsMarkAllReadRoute: ApiNotificationsMarkAllReadRoute,
  ApiNotificationsSettingsRoute: ApiNotificationsSettingsRoute,
  ApiNotificationsTestRoute: ApiNotificationsTestRoute,
  ApiNotificationsUnreadCountRoute: ApiNotificationsUnreadCountRoute,
  ApiOsSplatRoute: ApiOsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
